"""add email field to user

Revision ID: 457ee4ce5750
Revises: 101de838998e
Create Date: 2015-12-21 16:53:23.418000

"""

# revision identifiers, used by Alembic.
revision = '457ee4ce5750'
down_revision = '101de838998e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
